---
storage:
  storage1:
    name: storage1
    account: shkawan1
    container: foo
    saskey: #################################################
  storage2:
    name: storage2
    account: shkawan2
    container: bar
    saskey: #################################################

# select logics to select storage dispatch_by_filename, roundrobin
# roundrobin maybe the fastest
copy_module: roundrobin
copy_module_params:
  dispatch_by_filename:
    - name: "a-p"
      pattern: ^[a-p]
      storage: storage1
    - name: "q-z0-9"
      pattern: ^[q-z0-9]
      storage: storage2

mongodb:
# hostname: localhost
# port    : 
# user    : 
# password: 
  dbname  : azure
  collname: storage
